# @note currently github actions does not support `skip ci` commit message filtering
name: CI
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm ci
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
